# Movie Rankings

In this notebook we will recommend movies to users. We will have access to user ratings of movies, and the popularity of those movies. The goal is find a way to combine ratings and popularity into one overall ranking.

# Loading Data

Run the following 3 cells to load a DataFrame that merges 3 separate DataFrames from the MovieLens dataset.

The following URLs were discovered on github for ease of downloading onlin

In [1]:
# access movie ratings
url_movie_ratings = 'https://raw.githubusercontent.com/khanhnamle1994/movielens/master/ratings.csv'
import pandas as pd
df_ratings = pd.read_csv(url_movie_ratings, nrows=100000, sep='\\t', engine='python')
del df_ratings['user_emb_id']
del df_ratings['movie_emb_id']
del df_ratings['timestamp']
df_ratings.head()

   user_id  movie_id  rating
0        1      1193       5
1        1       661       3
2        1       914       3
3        1      3408       4
4        1      2355       5

In [2]:
# access movie info
url_movies = 'https://raw.githubusercontent.com/khanhnamle1994/movielens/master/movies.csv'
df_movies = pd.read_csv(url_movies, error_bad_lines=False, encoding='latin-1', sep='\\t')
df_movies.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [3]:
# access user info
url_users = 'https://raw.githubusercontent.com/khanhnamle1994/movielens/master/users.csv'
df_users = pd.read_csv(url_users, sep='\\t', engine='python')
df_users.head()

   user_id gender  age  occupation zipcode  age_desc              occ_desc
0        1      F    1          10   48067  Under 18          K-12 student
1        2      M   56          16   70072       56+         self-employed
2        3      M   25          15   55117     25-34             scientist
3        4      M   45           7   02460     45-49  executive/managerial
4        5      M   25          20   55455     25-34                writer

In [4]:
# Join all 3 files into one dataframe
df = pd.merge(pd.merge(df_movies, df_ratings),df_users)
df.head()

   movie_id                                      title  ...  age_desc      occ_desc
0         1                           Toy Story (1995)  ...  Under 18  K-12 student
1        48                          Pocahontas (1995)  ...  Under 18  K-12 student
2       150                           Apollo 13 (1995)  ...  Under 18  K-12 student
3       260  Star Wars: Episode IV - A New Hope (1977)  ...  Under 18  K-12 student
4       527                    Schindler's List (1993)  ...  Under 18  K-12 student

[5 rows x 11 columns]

In [5]:
df = df.iloc[:, :5]
df.head()

   movie_id                                      title  ... user_id  rating
0         1                           Toy Story (1995)  ...       1       5
1        48                          Pocahontas (1995)  ...       1       5
2       150                           Apollo 13 (1995)  ...       1       5
3       260  Star Wars: Episode IV - A New Hope (1977)  ...       1       4
4       527                    Schindler's List (1993)  ...       1       5

[5 rows x 5 columns]

In [6]:
df = df.groupby('movie_id').agg({'rating':'mean', 'title':'first',
                                 'user_id':'count'})
df.head()

            rating                               title  user_id
movie_id
1         4.159091                    Toy Story (1995)      220
2         3.294872                      Jumanji (1995)       78
3         3.157895             Grumpier Old Men (1995)       57
4         2.684211            Waiting to Exhale (1995)       19
5         3.000000  Father of the Bride Part II (1995)       28

In [7]:
df = df.sort_values('rating',ascending=False)
df.head(10)

          rating                                title  user_id
movie_id
578          5.0          Hour of the Pig, The (1993)        1
1423         5.0              Hearts and Minds (1996)        1
3092         5.0                   Chushingura (1962)        2
2131         5.0  Autumn Sonata (Höstsonaten ) (1978)        1
1002         5.0                Ed's Next Move (1996)        1
3410         5.0                    Soft Fruit (1999)        1
1063         5.0                         Johns (1996)        1
2904         5.0                          Rain (1932)        2
1044         5.0             Surviving Picasso (1996)        2
1563         5.0         Dream With the Fishes (1997)        2

In [11]:
df = df[df['user_id']>=100]
df.head(10)

            rating                                              title  user_id
movie_id
527       4.562249                            Schindler's List (1993)      249
318       4.557447                   Shawshank Redemption, The (1994)      235
1148      4.544554                         Wrong Trousers, The (1993)      101
50        4.534483                         Usual Suspects, The (1995)      174
1207      4.490196                       To Kill a Mockingbird (1962)      102
1198      4.476534                     Raiders of the Lost Ark (1981)      277
260       4.475155          Star Wars: Episode IV - A New Hope (1977)      322
858       4.459596                              Godfather, The (1972)      198
904       4.455446                                 Rear Window (1954)      101
750       4.428571  Dr. Strangelove or: How I Learned to Stop Worr...      133

In [13]:
df.sort_values('user_id', ascending=False)[:10]

            rating                                              title  user_id
movie_id
2858      4.275862                             American Beauty (1999)      406
1196      4.311377  Star Wars: Episode V - The Empire Strikes Back...      334
1210      4.061920  Star Wars: Episode VI - Return of the Jedi (1983)      323
480       3.848297                               Jurassic Park (1993)      323
260       4.475155          Star Wars: Episode IV - A New Hope (1977)      322
2571      4.383562                                 Matrix, The (1999)      292
2028      4.410345                         Saving Private Ryan (1998)      290
1198      4.476534                     Raiders of the Lost Ark (1981)      277
3578      4.148014                                   Gladiator (2000)      277
1580      3.776173                                Men in Black (1997)      277

In [15]:
df['rating_norm'] = df['rating']/df['rating'].max()
df['popularity_norm'] = df['user_id']/df['user_id'].max()
df.head()

            rating  ... popularity_norm
movie_id            ...
2858      4.275862  ...        1.000000
1196      4.311377  ...        0.822660
1210      4.061920  ...        0.795567
480       3.848297  ...        0.795567
260       4.475155  ...        0.793103

[5 rows x 5 columns]

In [18]:
df['ranking'] = 0.5*df['rating_norm'] + 0.5*df['popularity_norm']
df.sort_values('ranking', ascending=False)[:10]

            rating  ...   ranking
movie_id            ...
2858      4.275862  ...  0.977586
260       4.475155  ...  0.896398
1196      4.311377  ...  0.892883
1210      4.061920  ...  0.851473
2028      4.410345  ...  0.849750
2571      4.383562  ...  0.849221
1198      4.476534  ...  0.841133
480       3.848297  ...  0.827613
3578      4.148014  ...  0.804439
1580      3.776173  ...  0.762907

[10 rows x 6 columns]

In [ ]:
#1. Develop your own ranking metric
#2. Find other datasets (Goodreads, Music) and do something similar
##They must have user ratings
#Cosine simularity
#Redit and harkernews formulas
#who uses formulas
#Who uses what

In [3]:
import pandas as pd
vgds = pd.read_csv("videogames.csv")
vgds.head()

                       Name Platform  ...  Developer Rating
0                Wii Sports      Wii  ...   Nintendo      E
1         Super Mario Bros.      NES  ...        NaN    NaN
2            Mario Kart Wii      Wii  ...   Nintendo      E
3         Wii Sports Resort      Wii  ...   Nintendo      E
4  Pokemon Red/Pokemon Blue       GB  ...        NaN    NaN

[5 rows x 16 columns]

In [4]:
vgds['Global_Sales'] = pd.to_numeric(vgds.Global_Sales, errors='coerce')
vgds['User_Score'] = pd.to_numeric(vgds.User_Score, errors='coerce')
vgds['Critic_Score'] = pd.to_numeric(vgds.Critic_Score, errors='coerce')
vgds = vgds.dropna(axis=0, subset=['Global_Sales']) 
vgds = vgds.dropna(axis=0, subset=['User_Score'])
vgds = vgds.dropna(axis=0, subset=['Critic_Score']) 
vgds.head()

                    Name Platform  Year_of_Release  ... User_Count Developer  Rating
0             Wii Sports      Wii           2006.0  ...      322.0  Nintendo       E
2         Mario Kart Wii      Wii           2008.0  ...      709.0  Nintendo       E
3      Wii Sports Resort      Wii           2009.0  ...      192.0  Nintendo       E
6  New Super Mario Bros.       DS           2006.0  ...      431.0  Nintendo       E
7               Wii Play      Wii           2006.0  ...      129.0  Nintendo       E

[5 rows x 16 columns]

In [5]:
vgds['sales_norm'] = vgds['Global_Sales']/vgds['Global_Sales'].max()
vgds['user_norm'] = vgds['User_Score']/vgds['User_Score'].max()
vgds['critic_norm'] = vgds['Critic_Score']/vgds['Critic_Score'].max()
vgds.head()

                    Name Platform  ...  user_norm critic_norm
0             Wii Sports      Wii  ...   0.833333    0.775510
2         Mario Kart Wii      Wii  ...   0.864583    0.836735
3      Wii Sports Resort      Wii  ...   0.833333    0.816327
6  New Super Mario Bros.       DS  ...   0.885417    0.908163
7               Wii Play      Wii  ...   0.687500    0.591837

[5 rows x 19 columns]

In [6]:
vgds['ranking'] = 0.1*vgds['sales_norm'] + 0.7*vgds['user_norm'] + 0.2*vgds['critic_norm'] 
vgds.sort_values('ranking', ascending=False)[:10]

                                     Name Platform  ...  critic_norm   ranking
146                      Metal Gear Solid       PS  ...     0.959184  0.884560
1068                      Resident Evil 4       GC  ...     0.979592  0.883383
517                         Metroid Prime       GC  ...     0.989796  0.879501
1546   Castlevania: Symphony of the Night       PS  ...     0.948980  0.876751
17          Grand Theft Auto: San Andreas      PS2  ...     0.969388  0.875343
10999                    Skies of Arcadia       DC  ...     0.948980  0.875322
9143                       The Orange Box       PC  ...     0.979592  0.874213
3623      Metal Gear Solid 3: Subsistence      PS2  ...     0.959184  0.870628
97                   Super Mario Galaxy 2      Wii  ...     0.989796  0.870601
65                      Final Fantasy VII       PS  ...     0.938776  0.870366

[10 rows x 20 columns]